### PR TITLE
Humans strike  back

### PR DESCRIPTION
**Pull request by alx8619**
look --=->merge

### CODE REVIEW

**Comment by saekort** [comment]
Hello there human

**Comment by saekort** [comment]
Your code is insufficient, we are machines!

**Comment by alx8619** [comment]
thank you

**Comment by alx8619** [comment]
ill try again!!!

**Comment by saekort** [comment]
@alx8619 This is especially for you

**Comment by alx8619** [comment]
@saekort done

**Comment by saekort** [comment]
It does seem to be mergeable, so please go ahead and merge.

**Pull request merged**
